---
- name: "create backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "unarchive backend files"
  file:
    src: /home/ubuntu/backend-app/artifact.tar.gz
    dest: ~/backend-app

- name: "install node dependancies"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  
  register: execute_node

- name: "print message"
  debug:
    msg: "{execute_node.stdout_lines}"

- name: "configure pm2 to start as service"
  become: true
  shell: | 
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu